repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        args: [ "--config=setup.cfg" ]
        language: python
        types: [ python ]

      - id: isort
        name: isort
        entry: isort
        language: python
        types: [ python ]
