version: '3.9'

services:


  db:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init_db:/docker-entrypoint-initdb.d
    env_file:
      - .env.db



volumes:
  postgres_data: